export const seedProducts: Omit<Product, "id">[] = [
  // Chicken Products
  {
    name: "Layer Chicken (Hard)",
    category: "Poultry",
    price: 48,
    description: "Premium quality layer chicken, hard variety",
    imageName: "layer-chicken.png",
    stock: 50,
  },
  {
    name: "Layer Chicken (Back)",
    category: "Poultry Parts",
    price: 32,
    description: "Fresh chicken back portions",
    imageName: "chicken-back.png",
    stock: 40,
  },
  {
    name: "Chicken Brassils (Soft)",
    category: "Poultry",
    price: 40,
    description: "Soft variety chicken brassils",
    imageName: "chicken-brassils.png",
    stock: 45,
  },
  {
    name: "Chicken Back",
    category: "Poultry Parts",
    price: 28,
    description: "Fresh chicken back cuts",
    imageName: "chicken-back.png",
    stock: 35,
  },
  {
    name: "Drumsticks",
    category: "Poultry Parts",
    price: 45,
    description: "Juicy chicken drumsticks",
    imageName: "drumsticks.png",
    stock: 60,
  },
  {
    name: "Chicken Wings",
    category: "Poultry Parts",
    price: 56,
    description: "Fresh chicken wings, perfect for grilling",
    imageName: "chicken-wings.png",
    stock: 70,
  },
  {
    name: "Gizzard",
    category: "Poultry Parts",
    price: 38,
    description: "Fresh chicken gizzards",
    imageName: "gizzard.png",
    stock: 30,
  },

  // Turkey
  {
    name: "Turkey Wings",
    category: "Turkey",
    price: 62,
    description: "Premium turkey wings",
    imageName: "turkey-wings.png",
    stock: 25,
  },

  // Fish & Seafood
  {
    name: "Red Fish",
    category: "Fish & Seafood",
    price: 70,
    description: "Fresh red fish",
    imageName: "red-fish.png",
    stock: 20,
  },
  {
    name: "Abidjan Salmon",
    category: "Fish & Seafood",
    price: 70,
    description: "Premium Abidjan salmon",
    imageName: "abidjan-salmon.png",
    stock: 15,
  },
  {
    name: "Local Salmon",
    category: "Fish & Seafood",
    price: 44,
    description: "Fresh local salmon",
    imageName: "local-salmon.png",
    stock: 30,
  },
  {
    name: "P/S 16",
    category: "Fish & Seafood",
    price: 40,
    description: "Premium seafood P/S 16",
    imageName: "ps-16.png",
    stock: 25,
  },
  {
    name: "Tilapia",
    category: "Fish & Seafood",
    price: 70,
    description: "Fresh tilapia fish",
    imageName: "tilapia.png",
    stock: 35,
  },
  {
    name: "Cassava Fish",
    category: "Fish & Seafood",
    price: 45,
    description: "Traditional cassava fish",
    imageName: "cassava-fish.png",
    stock: 20,
  },

  // Sausages
  {
    name: "Royal Sausage",
    category: "Processed Meat",
    price: 18,
    description: "Premium royal sausages",
    imageName: "royal-sausage.png",
    stock: 80,
  },
  {
    name: "Sadia Sausage",
    category: "Processed Meat",
    price: 20,
    description: "Quality Sadia sausages",
    imageName: "sadia-sausage.png",
    stock: 75,
  },
  {
    name: "Prime Beef Sausage",
    category: "Processed Meat",
    price: 45,
    description: "Premium beef sausages",
    imageName: "prime-beef-sausage.png",
    stock: 50,
  },
  {
    name: "Pramag Chicken/Beef Sausage",
    category: "Processed Meat",
    price: 43,
    description: "Mixed chicken and beef sausages",
    imageName: "pramag-sausage.png",
    stock: 55,
  },

  // Beef Offals
  {
    name: "Sinews (Intini)",
    category: "Offals(Beef)",
    price: 50,
    description: "Beef sinews/intini",
    imageName: "sinews.png",
    stock: 20,
  },
  {
    name: "Intestines",
    category: "Offals(Beef)",
    price: 10,
    description: "Fresh beef intestines",
    imageName: "intestines.png",
    stock: 15,
  },
  {
    name: "Cow Leg",
    category: "Offals(Beef)",
    price: 10,
    description: "Fresh cow leg",
    imageName: "cow-leg.png",
    stock: 25,
  },
  {
    name: "Cow Meat",
    category: "Meat",
    price: 20,
    description: "Fresh cow meat",
    imageName: "cow-meat.png",
    stock: 40,
  },
];

export const seedCategories = [
  { name: "All", description: "All products" },
  { name: "Poultry", description: "Chicken and poultry products" },
  { name: "Turkey", description: "Turkey products" },
  { name: "Fish & Seafood", description: "Fresh fish and seafood" },
  { name: "Processed Meat", description: "Sausages and processed meats" },
  { name: "Poultry Parts", description: "Chicken parts and cuts" },
  { name: "Offals(Beef)", description: "Beef offals and parts" },
  { name: "Meat", description: "Fresh meat products" },
];
